#!/usr/bin/python3

import sys
import os
import psycopg2

action = sys.argv[1]
collection = sys.argv[2]
if len(sys.argv) > 3:
    item = sys.argv[3]
else:
    item = 0

conn = psycopg2.connect(os.environ['PGTT_URL'])
conn.autocommit = True
cursor = conn.cursor()

add_log = '''INSERT into directus_activity (action,collection,item) VALUES ( %s, %s, %s) ON CONFLICT DO NOTHING'''
cursor.execute(add_log, (action,collection,item,))

conn.close()
