#!/bin/bash

# scan [target]

scan(){
    echo -e "\nCISO360AI scan"
    domain="$1"
        mkdir -p /results/$domain
	    cd /results/$domain
        if [ ! -f exclude.txt ]; then
            echo autodiscover.$domain >> exclude.txt
            echo msoid.$domain >> exclude.txt
            echo sip.$domain >> exclude.txt
            echo lyncdiscover.$domain >> exclude.txt
        fi

    log_activity "scan" "domains" "Started scan on $domain"

    #rename old files
    for i in `ls -I "*.old" -I "exclude.txt"`; 
        do cp $i $i.old;
    done

    #whois
    echo -e "\nwhois scan"
    whois -H $domain | grep ": "| egrep -v '(*>>>*|*REDACTED*|*NOTICE*|*query*|*version*)' | tee domain.whois
    grep "Registrant Organization" domain.whois | cut -d ":" -f2 | xargs| sed 's/,/%2C/g' | sed 's/ /+/g'| egrep -v '(*Whois*|*whois*|*WHOIS*|*domains*|*DOMAINS*|*Domains*|*domain*|*DOMAIN*|*Domain*|*proxy*|*Proxy*|*PROXY*|*PRIVACY*|*privacy*|*Privacy*|*REDACTED*|*redacted*|*Redacted*|*DNStination*|*WhoisGuard*|*Protected*|*protected*|*PROTECTED*)'| tee domain.registrant
    grep "Registrant Organisation" domain.whois | cut -d ":" -f2 | xargs| sed 's/,/%2C/g' | sed 's/ /+/g'| egrep -v '(*Whois*|*whois*|*WHOIS*|*domains*|*DOMAINS*|*Domains*|*domain*|*DOMAIN*|*Domain*|*proxy*|*Proxy*|*PROXY*|*PRIVACY*|*privacy*|*Privacy*|*REDACTED*|*redacted*|*Redacted*|*DNStination*|*WhoisGuard*|*Protected*|*protected*|*PROTECTED*)' >> domain.registrant 
    curl -s "https://crt.sh/?q="$domain"&output=json" -o domain.crtsh.json

    #subfinder
    echo -e "\nsubfinder scan"
    log_activity "scan" "domains" "subfinder on $domain"

    subfinder -silent -d "$domain" | sort | uniq | tee domains.subfinder
        grep -v -f exclude.txt -x domains.subfinder | anew domains.txt

    #wayback domains, subdomains and urls
    echo -e "\nwayback domains, subdomains and urls"
    log_activity "scan" "domains" "wayback on $domain"

    curl -sk "https://web.archive.org/cdx/search/cdx?url=*."$domain"&output=txt&fl=original&collapse=urlkey&page=" | sort | uniq | tee urls.wayback
        cat urls.wayback | awk -F / '{gsub(/:.*/, "", $3); print $3}' | sort | uniq | tee domains.wayback
        grep -v -f exclude.txt -x domains.wayback | anew domains.txt

    #amass
	echo -e "\namass scan"
    log_activity "scan" "domains" "amass on $domain"
    timeout 120 amass enum -silent -passive -timeout 1 -norecursive -nolocaldb -noalts -blf exclude.txt -nf domains.txt -o domains.amass -config /scan_domain/config/amass.ini -d "$domain"
       grep -v -f exclude.txt -x domains.amass | anew domains.txt

    grep -v $domain -x domains.txt > subdomains.txt
    #logger -p syslog.notice -t $domain -f subdomains.txt

    import_scan $domain

    cd /results
    echo -e "\nEnumStop"
    log_activity "scan" "domains" "Finished scan on $domain"

}

scan $1 >> /proc/1/fd/1
