#!/usr/bin/python3

import sys
import os
import requests
import psycopg2
from urllib.parse import urlparse

#Establishing the connection
conn = psycopg2.connect(
   host = os.environ['POSTGRES_HOST'],
   database = os.environ['POSTGRES_DB'],
   port = os.environ['POSTGRES_PORT'],
   user = os.environ['POSTGRES_USER'],
   password = os.environ['POSTGRES_PASSWORD']
)
conn.autocommit = True
cursor = conn.cursor()


#Check database tables
add_table = '''
CREATE TABLE IF NOT EXISTS emails(
        email varchar(255) PRIMARY KEY,
        domain_id integer REFERENCES domains(id) ON DELETE CASCADE
);'''
cursor.execute(add_table)

add_table = '''
CREATE TABLE IF NOT EXISTS email_breaches(
        breach_id serial PRIMARY KEY,
        email varchar(255) REFERENCES emails(email) ON DELETE CASCADE,
        breach_date date NOT NULL,
        breach_location varchar(255) NOT NULL,
        scan_date date NOT NULL
);'''
cursor.execute(add_table)

print("Tables Checked")
conn.close()


#Check API
response = requests.get("https://haveIbeenpwned.com/api/v3/subscription/status", headers={'hibp-api-key':os.environ['HIBP_API_KEY']})
print("API Checked")
print(response.json())
