#!/usr/bin/python3

import sys
import os
import requests
import psycopg2
from urllib.parse import urlparse

#Establishing the connection
conn = psycopg2.connect(
   host = os.environ['POSTGRES_HOST'],
   database = os.environ['POSTGRES_DB'],
   port = os.environ['POSTGRES_PORT'],
   user = os.environ['POSTGRES_USER'],
   password = os.environ['POSTGRES_PASSWORD']
)
conn.autocommit = True
cursor = conn.cursor()


#Check database tables
erase_table = '''
DROP TABLE IF EXISTS emails CASCADE
;'''
cursor.execute(erase_table)

erase_table = '''
DROP TABLE IF EXISTS email_breaches
;'''
cursor.execute(erase_table)

add_table = '''
CREATE TABLE IF NOT EXISTS emails(
	id serial PRIMARY KEY,
	email varchar(255) NOT NULL,
        domain_id integer REFERENCES domains(id) ON DELETE CASCADE
);'''
cursor.execute(add_table)

add_table = '''
CREATE TABLE IF NOT EXISTS email_breaches(
        id serial PRIMARY KEY,
        email_id integer REFERENCES emails(id) ON DELETE CASCADE,
	breach_date date NOT NULL,
        breach_name varchar(255) NOT NULL,
        scan_date date NOT NULL
);'''
cursor.execute(add_table)

print("Tables Wipped")
conn.close()


#Wipe stored_breach
os.remove("stored_breach")
file = open("stored_breach", "x")
file.write("Wiped")
file.close()
print("Stored_breach Wiped")
