#!/usr/bin/python3

import sys
from datetime import datetime
import os
import requests
from requests.adapters import HTTPAdapter, Retry
import http
import psycopg2
import json
import logging

#TBD - Add logging to avoid - PYTHONUNBUFFERED=1
# https://stackoverflow.com/questions/29663459/why-doesnt-python-app-print-anything-when-run-in-a-detached-docker-container

# Redirect stdout to /proc/1/fd/1 to run in Docker
sys.stdout = open('/proc/1/fd/1', 'w')

# Check if an email parameter was provided
email_parameter = sys.argv[1] if len(sys.argv) > 1 else None

# Load the .env file
HIBP_API="https://haveibeenpwned.com/api/v3/"
HIBP_API_KEY = os.getenv('HIBP_API_KEY', 00000000000000000000000000000000)
USER_AGENT = os.getenv('USER_AGENT', 'CISO360.AI')

# Debug requests
# http.client.HTTPConnection.debuglevel = 1

def HIBP(url):
	s = requests.Session()
	retry_strategy = Retry(
		total=5,
		status_forcelist=[429, 500, 502, 503, 504],
		allowed_methods=["GET", "POST"],
		backoff_factor=2
		)
	adapter = HTTPAdapter(max_retries=retry_strategy)
	s.mount("https://", adapter)
	s.mount("http://", adapter)
	s.headers.update({
					'hibp-api-key': HIBP_API_KEY, 
					'user-agent': USER_AGENT,
					})
	response = s.get(url,timeout=5)
	return response

# Establishing the database connection
conn = psycopg2.connect(
   host = os.environ['POSTGRES_HOST'],
   database = os.environ['POSTGRES_DB'],
   port = os.environ['POSTGRES_PORT'],
   user = os.environ['POSTGRES_USER'],
   password = os.environ['POSTGRES_PASSWORD']
)
conn.autocommit = True
cursor = conn.cursor()

# Check for new data breaches by checking if the latest data breach is different from the localy stored one
print("*** Checking for new email breaches")
URL = HIBP_API + "latestbreach"
new_breach_found = False
try:
	response = HIBP(URL)
	latest_breach = response.json()['Name']
	print("Latest breach: " + latest_breach)
except:
	print(response)
	sys.exit(1)

if email_parameter:
    # Use the provided email parameter
	print("*** Fetching one email from the database ***")
	email_query = ''' SELECT (email, id) FROM emails WHERE status = 'active' and email = %s;'''
	cursor.execute(email_query, (email_parameter,))
	emails = cursor.fetchall()
	if len(emails) == 0:
		print("Email not found in the database")
		sys.exit(1)
else:
	print("*** Fetching all active emails from the database ***")
	emails_query = '''SELECT (email, id) FROM emails WHERE status = 'active';'''
	cursor.execute(emails_query)
	emails = cursor.fetchall()

for email_row in emails:
	report_emails = {}
	# Strip outer brackets and break into the two response components
	clean_database_response = email_row[0][1:-1].split(',')
	email = clean_database_response[0]
	domain = email.split('@')[1]
	print("Domain: " + str(domain))
	email_id = clean_database_response[1]

	print("\nChecking email: " + email)

	# Create email folder in /results if not existing
	if not os.path.exists("/results/" + domain):
		os.makedirs("/results/" + domain)
	
	now = datetime.now()
	email_stored_breach = "/results/" + domain + "/stored_breach-" + email
	filename = "/results/" + domain + "/HIBP-report-" + email + "-{}.txt".format(now.strftime("%d-%m-%Y-%H-%M-%S"))

	# Check if the stored breach is the same as the latest breach
	# If not, set new_breach_found to True
	try:
		file = open(email_stored_breach, "a+")
	except IOError as e:
		print(f"Unable to open file: {e}")
	file.seek(0)
	stored_breach = file.readline()
	if stored_breach == "":
		print("No stored breach found")
	else:
		print("Stored breach: " + stored_breach)
	file.close()

	if stored_breach != latest_breach: 
		new_breach_found = True

		print("\nCheck new breaches affecting: {}".format(email))
		URL = HIBP_API + "breachedaccount/{}/?truncateResponse=false".format(email)
		response = HIBP(URL)

		if response.status_code == 404:
			print("\nNothing found for: {}".format(email))
			api_breaches = []
		elif response.status_code == 200:
			api_breaches = response.json()
		else:
			print("API Error: {}".format(response.status_code))
			continue
		
		report_breaches = []

		for breach in api_breaches:
			breach_name = breach['Name']
			print("\tChecking breach: {}".format(breach_name))
			fetch_breach_exists = '''
				SELECT EXISTS(SELECT 1
				FROM breaches
				WHERE breaches.name = %s)
				;'''
			cursor.execute(fetch_breach_exists, (breach_name,))
			breach_exists = cursor.fetchall()[0][0]

			if breach_exists == False:
				breach_name = breach['Name']
				print("\tNew breach added: {}".format(breach_name))
				insert_new_breach = '''
					INSERT INTO breaches (name, breach_date, date_updated, title, domain, affected_data)
					VALUES (%s, %s, CURRENT_DATE, %s, %s, %s)
					RETURNING id;
				'''
				cursor.execute(insert_new_breach, (breach['Name'], breach['BreachDate'], breach['Title'], breach['Domain'], json.dumps(breach['DataClasses'])))
				breach_id = cursor.fetchone()[0]

			email_breach_exists ='''
				SELECT EXISTS(SELECT 1
				FROM breaches
				JOIN breaches_emails ON breaches.id = breaches_emails.breaches_id
				JOIN emails ON breaches_emails.emails_id = emails.id
				WHERE breaches.name = %s
				AND emails.email = %s)
				;'''
			cursor.execute(email_breach_exists, (breach['Name'], email))
			email_breach_exists = cursor.fetchall()[0][0]

			if email_breach_exists == False:
				print("\tEmail will be added: {}".format(breach['Name']))

				insert_new_breach_email = '''
						INSERT INTO breaches_emails (breaches_id, emails_id)
						VALUES ((SELECT id from breaches WHERE breaches.name = %s), %s)
						;'''
				cursor.execute(insert_new_breach_email, (breach['Name'], email_id))

				report_breaches.append(breach['Name'])

# Add the new breaches to the email for the report
		if len(report_breaches) > 0:
			report_emails[email] = report_breaches
		if len(report_emails) > 0:
			print("***** Generating Report *****")
			report_file = open(filename, "x")
			dt_string = now.strftime("%B %d %Y")
			report_file.write("# CISO360AI report - HIBP found emails \n")
			report_file.write("# Date: {}\n\n".format(dt_string))

			for email in report_emails:
				report_file.write("\t{}\n".format(email))
				for breach in report_emails[email]:
					report_file.write("\t\t{}\n".format(breach))

			report_file.close()
			print("***** Report saved at {} *****".format(filename))
		else:
			print("***** No report to generate *****")
	else:
		print("*** No new breaches detected ***")
	# Update stored_breach after successful scan
	os.remove(email_stored_breach)
	file = open(email_stored_breach, "x")
	file.write(latest_breach)
	file.close()
