#!/usr/bin/python3

import sys
from datetime import datetime
import os
import requests
from requests.adapters import HTTPAdapter, Retry
import http
import psycopg2
import json

# Redirect stdout to /proc/1/fd/1 to run in Docker
sys.stdout = open('/proc/1/fd/1', 'w')

# Check if a domain parameter was provided
domain_parameter = sys.argv[1] if len(sys.argv) > 1 else None

# Load the .env file
HIBP_API="https://haveibeenpwned.com/api/v3/"
HIBP_API_KEY = os.getenv('HIBP_API_KEY', 00000000000000000000000000000000)
USER_AGENT = os.getenv('USER_AGENT', 'CISO360.AI')

# Debug requests
# http.client.HTTPConnection.debuglevel = 1

def HIBP(url):
	s = requests.Session()
	retry_strategy = Retry(
		total=5,
		status_forcelist=[429, 500, 502, 503, 504],
		allowed_methods=["GET", "POST"],
		backoff_factor=2
		)
	adapter = HTTPAdapter(max_retries=retry_strategy)
	s.mount("https://", adapter)
	s.mount("http://", adapter)
	s.headers.update({
					'hibp-api-key': HIBP_API_KEY, 
					'user-agent': USER_AGENT,
					})
	response = s.get(url,timeout=5)
	return response

# Establishing the database connection
conn = psycopg2.connect(
   host = os.environ['POSTGRES_HOST'],
   database = os.environ['POSTGRES_DB'],
   port = os.environ['POSTGRES_PORT'],
   user = os.environ['POSTGRES_USER'],
   password = os.environ['POSTGRES_PASSWORD']
)
conn.autocommit = True
cursor = conn.cursor()

# Check for new data breaches by checking if the latest data breach is different from the localy stored one
print("*** Checking for new breaches")
URL = HIBP_API + "latestbreach"
new_breach_found = False
try:
	response = HIBP(URL)
	latest_breach = response.json()['Name']
	print("Latest breach: " + latest_breach)
except:
	print(response)
	sys.exit(1)

if domain_parameter:
    # Use the provided email parameter
	print("*** Fetching one domain from the database ***")
	domain_query = ''' SELECT (domain, id) FROM domains WHERE status = 'active' and domain = %s;'''
	cursor.execute(domain_query, (domain_parameter,))
	domains = cursor.fetchall()
	if len(domains) == 0:
		print("Domain not found in the database")
		sys.exit(1)
else:
	print("*** Fetching all active domains from the database ***")
	domains_query = '''SELECT (domain, id) FROM domains;'''
	cursor.execute(domains_query)
	domains = cursor.fetchall()

for domain_row in domains:
	report_emails = {}
	# Strip outer brackets and break into the two response components
	clean_database_response = domain_row[0][1:-1].split(',')
	domain = clean_database_response[0]
	domain_id = clean_database_response[1]

	print("\nChecking domain: " + domain)

	# Create domain folder in /results if not existing
	if not os.path.exists("/results/" + domain):
		os.makedirs("/results/" + domain)
	
	now = datetime.now()
	domain_stored_breach = "/results/" + domain + "/stored_breach"
	filename = "/results/" + domain + "/HIBP-report-domain-{}.txt".format(now.strftime("%d-%m-%Y-%H-%M-%S"))

	# Check if the stored breach is the same as the latest breach
	# If not, set new_breach_found to True
	try:
		file = open(domain_stored_breach, "a+")
	except IOError as e:
		print(f"Unable to open file: {e}")
	file.seek(0)
	stored_breach = file.readline()
	if stored_breach == "":
		print("No stored breach found")
	else:
		print("Stored breach: " + stored_breach)
	file.close()

	if stored_breach != latest_breach: 
		new_breach_found = True
		print("\nCheck new breaches affecting: {}".format(domain))
		URL = HIBP_API + "breacheddomain/{}".format(domain)
		response = HIBP(URL)

		if response.status_code == 404:
			print("\nNothing found for: {}".format(domain))
			dict_response = []
		elif response.status_code == 200:
			dict_response = response.json()
		else:
			print("API Error: {}".format(response.status_code))
			continue

		emails_to_update = [] # List for storing emails that need updating in each domain

		#################
		# Email check
		#################
		# For each breached email the API returned
		# Check if it exists in the database (If not, Add it)
		# Check the number of breaches the API returned with the number stored in the database
		# If the number the API returned is greater, add the email to the list emails_to_update
		for email in dict_response:
			full_email = email + "@" + domain
			fetch_email_exists = ''' 
								SELECT EXISTS(
								SELECT 1 
								FROM emails 
								WHERE email = %s)
								;'''
			cursor.execute(fetch_email_exists, (full_email,))
			email_exists = cursor.fetchall()[0][0]

			if email_exists == False:
				insert_new_email = 	''' 
					INSERT INTO emails(id, email, domain_id) 
					VALUES (gen_random_uuid(), %s, %s);'''
				cursor.execute(insert_new_email, (full_email, domain_id))
				print("\tNew Email: " + full_email)

			fetch_breach_count = '''
				SELECT COUNT(*)
				FROM breaches
				JOIN breaches_emails ON breaches.id = breaches_emails.breaches_id
				JOIN emails ON breaches_emails.emails_id = emails.id
				WHERE emails.email = %s;'''
			cursor.execute(fetch_breach_count, (full_email,))
			email_breach_count = cursor.fetchall()[0][0]

			if email_breach_count < len(dict_response[email]):
				emails_to_update.append(full_email)

		# Display if the domain has any emails to update
		if len(emails_to_update) > 0:
			print("\n********* List of emails that need updating ********")
			print(emails_to_update) #temp
		else:
			print("\tNothing to update in this domain")

		print()

		report_breaches = [] # List for storing newly added breaches for the final report


		#############
		# Email Updating
		#############
		# For each email that needs updating
		# Fetch the emails database id
		#   For each breach the email has in the API response
		#   Check if the breach exists in our database
		#   If not, add it to the database and the new breaches list
		for email in emails_to_update:

			print("\nChecking the email: {}".format(email))
			URL = HIBP_API + "breachedaccount/{}/?truncateResponse=false".format(email)
			response = HIBP(URL)
			api_breaches = response.json()

			fetch_email_id ='''
						SELECT id
						FROM emails
						WHERE email = %s;'''
			cursor.execute(fetch_email_id, (email,))
			email_id = cursor.fetchall()[0][0]

			for breach in api_breaches:

				fetch_breach_exists = '''
					SELECT EXISTS(SELECT 1
					FROM breaches
					WHERE breaches.name = %s);'''
				cursor.execute(fetch_breach_exists, (breach['Name'],))
				breach_exists = cursor.fetchall()[0][0]

				if breach_exists == False:
					print("\tNew breach added: {}".format(breach['Name']))
					insert_new_breach = '''
					INSERT INTO breaches (name, breach_date, date_updated, title, domain, affected_data)
					VALUES (%s, %s, CURRENT_DATE, %s, %s, %s)
					RETURNING id;'''
					cursor.execute(insert_new_breach, (breach['Name'], breach['BreachDate'], breach['Title'], breach['Domain'], json.dumps(breach['DataClasses'])))
					breach_id = cursor.fetchone()[0]

				email_breach_exists ='''
				SELECT EXISTS(SELECT 1
				FROM breaches
				JOIN breaches_emails ON breaches.id = breaches_emails.breaches_id
				JOIN emails ON breaches_emails.emails_id = emails.id
				WHERE breaches.name = %s
				AND emails.email = %s)
				;'''
				cursor.execute(email_breach_exists, (breach['Name'], email))
				email_breach_exists = cursor.fetchall()[0][0]

				if email_breach_exists == False:
					print("\tEmail will be added: {}".format(breach['Name']))

					insert_new_breach_email = '''
						INSERT INTO breaches_emails (breaches_id, emails_id)
						VALUES ((SELECT id from breaches WHERE breaches.name = %s), %s)
						;'''
					cursor.execute(insert_new_breach_email, (breach['Name'], email_id))

					report_breaches.append(breach['Name'])

	# Add in the new breaches to the email and domain dicts for the report
			if len(report_breaches) > 0:
				report_emails[email] = report_breaches
		if len(report_emails) > 0:
				# report_domains[domain] = report_emails
		# if len(report_domains) > 0:
			print("***** Generating Report *****")
			report_file = open(filename, "x")
			dt_string = now.strftime("%B %d %Y")
			report_file.write("# CISO360AI report - HIBP found emails \n")
			report_file.write("# Date: {}\n\n".format(dt_string))

			for email in report_emails:
				report_file.write("\t{}\n".format(email))
				for breach in report_emails[email]:
					report_file.write("\t\t{}\n".format(breach))

			report_file.close()
			print("***** Report saved at {} *****".format(filename))
		else:
			print("***** No report to generate *****")
	else:
		print("*** No new breaches detected ***")
	# Update stored_breach after successful scan
	os.remove(domain_stored_breach)
	file = open(domain_stored_breach, "x")
	file.write(latest_breach)
	file.close()

