#!/bin/bash

# scan [target]

scan(){
    echo -e "\nCISO360AI scan"
    target="$1"

    mkdir -p /results/$target
    cd /results/$target

    log_activity "scan" "TLS" #"Started scan on $target"

    echo -e "\nTestSSL scan"
    timeout $TIMEOUT_SHORT testssl --ip one --ids-friendly -oJ /results/$target/testssl.json --overwrite $target

    import_scan $target

    cd /results
    echo -e "\nEnumStop"
    log_activity "scan" "TLS" #"Finished scan on $target"
}

scan $1 >> /proc/1/fd/1
