#!/bin/bash

# scan [target]

# Function to check if a string is a valid IP address
is_valid_ip() {
    local ip=$1
    local valid_ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"

    if [[ $ip =~ $valid_ip_regex ]]; then
        # Check if each octet is between 0 and 255
        IFS='.' read -r -a octets <<< "$ip"
        for octet in "${octets[@]}"; do
            if ((octet < 0 || octet > 255)); then
                echo "Invalid IP address"
                return 1
            fi
        done
        echo "Valid IP address"
        return 0
    else
        echo "Invalid IP address"
        return 1
    fi
}

scan(){
    echo -e "\nCISO360AI scan"
    target="$1"

    mkdir -p /results/$target
    cd /results/$target

    log_activity "scan" "TLS" #"Started scan on $target"

    echo -e "\nTestSSL scan"

    if is_valid_ip $target; then
        timeout $TIMEOUT_SHORT testssl --quiet --sneaky --connect-timeout 2 --openssl-timeout 2 -p -s -S -U -oJ /results/$target/testssl.json --overwrite $target
    else
        timeout $TIMEOUT_SHORT testssl --quiet --sneaky --ip one --connect-timeout 2 --openssl-timeout 2 -p -s -S -U -oJ /results/$target/testssl.json --overwrite $target
    fi
    if [ $? -ne 0 ]; then
        echo "TestSSL scan failed"
        exit 1
    fi
    
    import_scan $target

    cd /results
    echo -e "\nEnumStop"
    log_activity "scan" "TLS" #"Finished scan on $target"
}

scan $1 >> /proc/1/fd/1
